### ISSUE TITLE
Nuclear Magnetic Resosnace Spectrocopy and Evaulation of Simple 1H NMR Spectra of Select Organic Compounds 

### ISSUE THREAD

**Issue by 2Shabby** [virtual-labs/physical-chemistry-iiith#149]
Defect Description:
On certain browsers the solutions are all displayed in the beginning, before the questions are even displayed.
Expected Result:
Answer should be displayed only after the question is answered.
![Issue18](https://user-images.githubusercontent.com/43069865/54489217-0ec99480-48d0-11e9-9e26-5f96aa0b4392.png)

**Comment by AkashV420** [comment]
fixed !
commit id : https://github.com/virtual-labs/physical-chemistry-iiith/pull/192/commits/d52091d3e4489f9d37b2e4724f5f9fa31f72b394
