### ISSUE TITLE
QA_PhysicalChemistry_brokenlinks_in_lab

### ISSUE THREAD

**Issue by sadhanareddy** [virtual-labs/physical-chemistry-iiith#5]
Defect Description :
In this lab following links are not working, they are redirecting to an error page. Whereas it should redirect to an appropriate page.

Exp1 Theory page - 1st link(404 error)
Exp1 Further readings page, in  "**other references section**"  -  2,4,6(404 error) 7,9,12(503 error) links
Exp1 Further readings page  in **sample preparation** section -  3rd link ( 404 error)
Exp2 Further readings page - 2,4,6 (404 error ) 7th,10th,13th (503 error) links
Exp5 Further readings page - 6th link (404 error ) 
Exp6 Further readings page - 6th link (404 error ) 

Actual Result :
In this lab following links are not working, they are redirecting to an error page. 

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attachment:
Find the screenshots of the brokenlinks in the zip file:
[broken_links.zip](https://github.com/Virtual-Labs/physical-chemistry-iiith/files/566238/broken_links.zip)

**Comment by sravanthimodepu** [comment]
1. Updated the proper link in the exp1 theory page - 1st link and exp6 further readings 6th link.
2. Removed the below links, as they are not available:
- Exp1 Further readings page, in "other references section" - 2,4,6(404 error) 7,9,12(503 error) links
- Exp1 Further readings page in sample preparation section - 3rd link ( 404 error)
- Exp2 Further readings page - 2,4,6, 7, 10,13 links
- Exp2 Further readings page - 2,4,6, 7, 10,13 links
- Exp5 Further readings page - 2nd & 6th link.
