### ISSUE TITLE
 QA_PhysicalChemistry_brokenlink_in edx 

### ISSUE THREAD

**Issue by sadhanareddy** [virtual-labs/physical-chemistry-iiith#6]
Defect Description :
In the openedx "instructor" link which is in all the pages is giving 404 eror.

Actual Result :
link is giving 404 eror.

Environment :
OS: Windows 7, Ubuntu-16.04, Centos-6
Browsers: Firefox-42.0,Chrome-47.0,chromium-45.0
Bandwidth : 100Mbps
Hardware Configuration:8GBRAM,
Processor:i5

Attatchment:
Find screenshot below.
![instructor](https://cloud.githubusercontent.com/assets/11345237/19992593/3bc8cbd6-a265-11e6-80ac-8af8a1b5972a.png)

**Comment by sravanthimodepu** [comment]
Issue is keeping on hold, as the system's team will work on this.
